# Generated by Django 2.2 on 2020-08-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published_date', models.CharField(max_length=10)),
                ('average_rating', models.PositiveSmallIntegerField()),
                ('ratings_count', models.PositiveIntegerField()),
                ('thumbnail', models.URLField()),
                ('authors', models.ManyToManyField(blank=True, default='Not available', related_name='books', to='books.Author')),
                ('categories', models.ManyToManyField(blank=True, default='', related_name='books', to='books.Category')),
            ],
        ),
    ]
